# Esta plantilla de AWS SAM se ha generado a partir de la configuración de su
# función. Si su función tiene uno o más desencadenadores, tenga en cuenta que los
# recursos de AWS asociados a estos desencadenadores no están completamente
# especificados en esta plantilla e incluyen valores de marcadores de posición.
# Abra esta plantilla en AWS Application Composer o en su IDE favorito y
# modifíquela para especificar una aplicación sin servidor con otros recursos de
# AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  pruebalambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Layers:
        - !Ref Layer1
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:sa-east-1:025066252853:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:sa-east-1:025066252853:log-group:/aws/lambda/prueba_lambda:*
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path:
              name: /
              url: ' '
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path:
              name: /
              url: ' '
            Method: DELETE
        Api3:
          Type: Api
          Properties:
            Path:
              name: /
              url: ' '
            Method: PUT
        Api4:
          Type: Api
          Properties:
            Path:
              name: /
              url: ' '
            Method: GET
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
  # This resource represents your Layer with name prueba_lambda. To download the
# content of your Layer, go to
# 
# aws.amazon.com/go/view?arn=arn%3Aaws%3Alambda%3Asa-east-1%3A025066252853%3Alayer%3Aprueba_lambda%3A1&source=lambda
  Layer1:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./prueba_lambda
      LayerName: prueba_lambda
      CompatibleRuntimes:
        - nodejs20.x
        - nodejs18.x
        - nodejs16.x
